###
GET {{host}}/image/man-doing-jumping-jacks-star.png?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb2RlIjoiYWRtaW4iLCJpZCI6IjY2YWY3OTQ2ZWU5OTFhNzc3MWZjZTFkYiIsImlhdCI6MTcyMjc3Nzk4OCwiZXhwIjoxNzIyODA2Nzg4fQ.6KEoqIG17fQjX9jLreKbKabIGNJ0-CHm1OmF2lyk6nw&height=50