###
POST {{host}}/graphql
Content-Type: application/json
Authorization: Bearer {{token}}
X-REQUEST-TYPE: GraphQL

query trainings {
  trainings {
    id
    slug
    workout {
      slug
      sets {
        rep
        slugs
        duration
        rest
        pause
        sets {
          rep
          slugs
          duration
          rest
          pause
          sets {
            rep
            slugs
            duration
            rest
            pause
          }
        }
      }
    }
  }
}