###
POST {{host}}/graphql
Content-Type: application/json
Authorization: Bearer {{token}}
X-REQUEST-TYPE: GraphQL

query {
  users {
    id
    code
    name_first
    name_last
    description
    mail
    role
  }
}

###
POST {{host}}/graphql
Content-Type: application/json
Authorization: Bearer {{token}}
X-REQUEST-TYPE: GraphQL

query {
  user (
    dto: {
      id: "65d615385688080e0a0f0ec2"
      #code: "faro"
    }
  ) {
    id
    code
    name_first
    name_last
    description
    mail
    role
  }
}

###
POST {{host}}/graphql
Content-Type: application/json
Authorization: Bearer {{token}}
X-REQUEST-TYPE: GraphQL

mutation {
  create_user (
    dto: {
      code: "user"
      password: "pass"
      name_first: "name_first"
      name_last: "name_last"
      description: "description"
      mail: "mail"
    }
  ) {
    id
    code
    name_first
    name_last
    description
    mail
    role
  }
}
