export enum ERRORS {
  AUTH_PASSKEY_USECASE_FAIL = 'AUTH_PASSKEY_USECASE_FAIL',
  BDD_SERVICE_SQL_NO_FILTER = 'BDD_SERVICE_SQL_NO_FILTER',
  GET_CHEST_USECASE_WRONG_SECRET = 'GET_CHEST_USECASE_WRONG_SECRET',
  GET_USER_USECASE_USER_NOT_FOUND = 'GET_USER_USECASE_USER_NOT_FOUND',
  GET_CHEST_USECASE_CHEST_NOT_FOUND = 'GET_CHEST_USECASE_CHEST_NOT_FOUND',
  GET_THING_USECASE_THING_NOT_FOUND = 'GET_THING_USECASE_THING_NOT_FOUND',
  GET_CHEST_USECASE_USER_NOT_IN_MEMBERS = 'GET_CHEST_USECASE_USER_NOT_IN_MEMBERS',
  CREATE_USER_USECASE_USER_ALREADY_EXIST = 'CREATE_USER_USECASE_USER_ALREADY_EXIST',
}
